version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "dist/**",
    "examples/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/slackhq/nebula"]
